all: compile

compile:
	java -jar ./jar/jtb132di.jar -te minijava.jj
	java -jar ./jar/javacc5.jar minijava-jtb.jj
	javac MiniJavac.java

clean:
	rm -f *.class *~

#Delete all extra files generated by jtb and javacc as well
clean-all:
	rm -f *.class *~
	rm -rf syntaxtree/ visitor/
	rm minijava-jtb.jj
	rm MiniJavaParser.java MiniJavaParserConstants.java MiniJavaParserTokenManager.java
	rm JavaCharStream.java ParseException.java
	rm Token.java TokenMgrError.java
